version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  target-branch: develop
  assignees:
  - jonfairbanks
  versioning-strategy: increase
  ignore:
  - dependency-name: next-auth
    versions:
    - 3.17.1
    - 3.17.2
    - 3.18.0
    - 3.18.2
    - 3.19.0
    - 3.19.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.3
  - dependency-name: "@material-ui/core"
    versions:
    - 3.9.4
    - 4.11.3
  - dependency-name: react-dom
    versions:
    - 16.13.0
  - dependency-name: mongoose
    versions:
    - 5.12.4
